### PR TITLE
Run commands in an atom terminal emulator instead of a buffered process

### PR DESCRIPTION
**Pull request by nolanpro**
Hey @moxley Thanks for the package, I use it a bunch! Once issue I had was not being able to step into a debug like binding.pry because the command output is a buffered process. I replaced that with making calls to the platformio-ide-terminal package on my fork and it seems to work great. What are your thoughts on this? Thanks!

### CODE REVIEW

**Comment by moxley** [comment]
*mind blown* Thank you @nolanpro! This works very well, and it's going to make a lot of people happy.

**Comment by moxley** [comment]
@nolanpro: I'll review this over the next several days.

**Comment by moxley** [comment]
@nolanpro This is looking really good. What's the key binding for closing the window pane, or canceling the test?

**Comment by nolanpro** [comment]
@moxley Thanks! I might need to rework how the commands go through to the terminal. I'll take a look at it this week and update the PR

**Comment by nolanpro** [comment]
@moxley I added back in toggle and cancel. Cancel just sends the close command to the terminal plugin which effectively cancels the process. Let me know what you think. Thanks!

**Comment by moxley** [comment]
It works! This is exciting. Thank you @nolanpro, for this excellent contribution to ruby-test.

**Comment by nolanpro** [comment]
@moxley Thanks! I'll keep an eye on this repo in case any issues come up related to the terminal

**Pull request merged**
