### PR TITLE
Fix RubyTest spec

### PR DESCRIPTION
**Pull request by moiristo**

### CODE REVIEW

**Comment by moiristo** [comment]
@moxley it works! 🎉

**Comment by moxley** [comment]
Thank you @moiristo !

**Comment by moxley** [comment]
@moiristo: I sent you an invite to be a collaborator to this project.

**Comment by moiristo** [comment]
@moxley Thanks! I'm not sure if I can be of much help as this was my only experience with an atom package, but as I'm still using it I think I can at least know firsthand when something is broken and test/approve PRs for it.

**Pull request merged**
